version: "3"
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=dbtest
      - MYSQL_ROOT_PASSWORD=root-password
    ports:
      - '3307:3306'
    volumes:
      - ./data:/data/db
